# Generated by Django 5.1.5 on 2026-05-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                (
                    "short_description",
                    models.CharField(
                        help_text="One-line summary shown in cards and the home grid.",
                        max_length=240,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Long-form description for the services page."
                    ),
                ),
                (
                    "icon_key",
                    models.CharField(
                        default="shield",
                        help_text="Icon identifier — matched in templates/partials/icons.html.",
                        max_length=40,
                    ),
                ),
                (
                    "capabilities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of bullet capabilities, e.g. ["24/7 SOC", "MITRE ATT&CK mapped"].',
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "title"],
            },
        ),
    ]
