# Generated by Django 5.1.5 on 2026-09-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="anchor",
            field=models.SlugField(
                blank=True,
                help_text="In-page anchor used by the services page and home links.",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="intro",
            field=models.TextField(
                blank=True, help_text="Opening paragraph on the services page."
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="outcome",
            field=models.CharField(
                blank=True, help_text="Single-line outcome statement.", max_length=240
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="tag",
            field=models.CharField(
                blank=True,
                help_text='Small mono label above the title, e.g. "01".',
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="icon_key",
            field=models.CharField(
                choices=[
                    ("shield", "Shield"),
                    ("cloud", "Cloud"),
                    ("radar", "Radar"),
                    ("siren", "Siren"),
                    ("lock", "Lock"),
                    ("compass", "Compass"),
                    ("grid", "Grid"),
                    ("pulse", "Pulse"),
                    ("cert", "Cert"),
                    ("nodes", "Nodes"),
                ],
                default="shield",
                help_text="Pick from the built-in icon set.",
                max_length=40,
            ),
        ),
    ]
