# Generated by Django 5.2.17 on 2026-09-17 21:02

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_service_anchor_service_intro_service_outcome_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="capabilities",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of bullet capabilities, e.g. ["24/7 SOC", "MITRE ATT&CK mapped"].',
                validators=[apps.core.validators.validate_string_list],
            ),
        ),
    ]
