# Generated by Django 5.1.5 on 2026-05-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                ("work_email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("company", models.CharField(max_length=160)),
                ("job_title", models.CharField(blank=True, max_length=120)),
                ("country", models.CharField(blank=True, max_length=80)),
                (
                    "organization_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1_50", "1 – 50 employees"),
                            ("51_500", "51 – 500 employees"),
                            ("501_2000", "501 – 2,000 employees"),
                            ("2001_10000", "2,001 – 10,000 employees"),
                            ("10001_plus", "10,001+ employees"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "interest",
                    models.CharField(
                        choices=[
                            ("threat_detection", "Threat Detection & Response"),
                            ("cloud_security", "Cloud Security"),
                            ("infrastructure", "Infrastructure Protection"),
                            ("incident_response", "Incident Response"),
                            ("zero_trust", "Zero Trust Architecture"),
                            ("consulting", "Security Consulting"),
                            ("partnership", "Partnership / Alliance"),
                            ("general", "General Inquiry"),
                        ],
                        default="general",
                        max_length=40,
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_handled", models.BooleanField(default=False)),
                ("handled_by", models.CharField(blank=True, max_length=120)),
                ("internal_notes", models.TextField(blank=True)),
                ("user_agent", models.CharField(blank=True, max_length=400)),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "verbose_name": "Contact Inquiry",
                "verbose_name_plural": "Contact Inquiries",
                "ordering": ["-created_at"],
            },
        ),
    ]
