# Generated by Django 5.2.17 on 2026-09-17 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contactinquiry",
            name="notified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set when the notification email was accepted for delivery. Empty means nobody was told about this inquiry.",
                null=True,
            ),
        ),
        # handled_by changes from free text to a real account reference.
        # Dropping and re-adding avoids trying to coerce the old CharField
        # values (including the empty string) into a foreign key, which no
        # backend accepts. The previous values were unauthenticated
        # self-assertions with no link to an account, so nothing recoverable
        # is lost; note the column is cleared.
        migrations.RemoveField(
            model_name="contactinquiry",
            name="handled_by",
        ),
        migrations.AddField(
            model_name="contactinquiry",
            name="handled_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member who took ownership. A real account, so this cannot be self-asserted free text.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="handled_inquiries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
