# Generated by Django 5.1.5 on 2026-09-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to hide from the site without deleting.",
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("body", models.TextField()),
            ],
            options={
                "verbose_name": "Company Value",
                "verbose_name_plural": "Company Values",
                "ordering": ["display_order", "pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CulturePillar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to hide from the site without deleting.",
                    ),
                ),
                ("tag", models.CharField(max_length=60)),
                ("title", models.CharField(max_length=140)),
                ("body", models.TextField()),
            ],
            options={
                "verbose_name": "Culture Pillar",
                "verbose_name_plural": "Culture Pillars",
                "ordering": ["display_order", "pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExpertisePillar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to hide from the site without deleting.",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        help_text="Small mono label above the title.", max_length=60
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("body", models.TextField()),
            ],
            options={
                "verbose_name": "Expertise Pillar",
                "verbose_name_plural": "Expertise Pillars",
                "ordering": ["display_order", "pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HomeFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to hide from the site without deleting.",
                    ),
                ),
                (
                    "icon_key",
                    models.CharField(
                        choices=[
                            ("shield", "Shield"),
                            ("cloud", "Cloud"),
                            ("radar", "Radar"),
                            ("siren", "Siren"),
                            ("lock", "Lock"),
                            ("compass", "Compass"),
                            ("grid", "Grid"),
                            ("pulse", "Pulse"),
                            ("cert", "Cert"),
                            ("nodes", "Nodes"),
                        ],
                        default="shield",
                        help_text="Pick from the built-in icon set.",
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("body", models.TextField()),
            ],
            options={
                "verbose_name": "Home Feature",
                "verbose_name_plural": "Home Features",
                "ordering": ["display_order", "pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HomeStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to hide from the site without deleting.",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text='The number, e.g. "99.97".', max_length=20
                    ),
                ),
                (
                    "suffix",
                    models.CharField(
                        blank=True,
                        help_text='Accent-coloured suffix, e.g. "%" or "+".',
                        max_length=10,
                    ),
                ),
                ("label", models.CharField(max_length=120)),
            ],
            options={
                "verbose_name": "Home Stat",
                "verbose_name_plural": "Home Stats",
                "ordering": ["display_order", "pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LeadershipMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to hide from the site without deleting.",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("role", models.CharField(max_length=140)),
                ("bio", models.TextField()),
                (
                    "initials",
                    models.CharField(
                        help_text='Shown in the avatar circle, e.g. "HA".', max_length=4
                    ),
                ),
            ],
            options={
                "verbose_name": "Leadership Member",
                "verbose_name_plural": "Leadership",
                "ordering": ["display_order", "pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Sectrex Consulting", max_length=120),
                ),
                ("tagline", models.CharField(blank=True, max_length=200)),
                (
                    "description",
                    models.TextField(
                        help_text="Default meta description, used when a page does not set one."
                    ),
                ),
                ("keywords", models.CharField(blank=True, max_length=400)),
                (
                    "url",
                    models.URLField(
                        default="https://sectrexconsulting.com",
                        help_text="Canonical public URL, used to build absolute links.",
                    ),
                ),
                (
                    "twitter",
                    models.CharField(
                        blank=True, help_text='Including the "@".', max_length=40
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("address", models.CharField(blank=True, max_length=240)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="TimelineEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to hide from the site without deleting.",
                    ),
                ),
                ("year", models.CharField(max_length=10)),
                ("title", models.CharField(max_length=140)),
                ("body", models.TextField()),
            ],
            options={
                "verbose_name": "Timeline Entry",
                "verbose_name_plural": "Timeline",
                "ordering": ["display_order", "pk"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TrustedByLogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to hide from the site without deleting.",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
            ],
            options={
                "verbose_name": "Trusted-By Entry",
                "verbose_name_plural": "Trusted-By Entries",
                "ordering": ["display_order", "pk"],
                "abstract": False,
            },
        ),
    ]
