# Generated by Django 5.1.5 on 2026-09-17 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_import_existing_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companyvalue",
            options={
                "ordering": ["display_order", "pk"],
                "verbose_name": "About · Value",
                "verbose_name_plural": "About · Values",
            },
        ),
        migrations.AlterModelOptions(
            name="culturepillar",
            options={
                "ordering": ["display_order", "pk"],
                "verbose_name": "Careers · Culture Pillar",
                "verbose_name_plural": "Careers · Culture",
            },
        ),
        migrations.AlterModelOptions(
            name="expertisepillar",
            options={
                "ordering": ["display_order", "pk"],
                "verbose_name": "About · Expertise Area",
                "verbose_name_plural": "About · Expertise",
            },
        ),
        migrations.AlterModelOptions(
            name="homefeature",
            options={
                "ordering": ["display_order", "pk"],
                "verbose_name": "Home · Why Sectrex Card",
                "verbose_name_plural": "Home · Why Sectrex",
            },
        ),
        migrations.AlterModelOptions(
            name="homestat",
            options={
                "ordering": ["display_order", "pk"],
                "verbose_name": "Home · Measured Outcome",
                "verbose_name_plural": "Home · Measured Outcomes",
            },
        ),
        migrations.AlterModelOptions(
            name="leadershipmember",
            options={
                "ordering": ["display_order", "pk"],
                "verbose_name": "About · Leader",
                "verbose_name_plural": "About · Leadership",
            },
        ),
        migrations.AlterModelOptions(
            name="timelineentry",
            options={
                "ordering": ["display_order", "pk"],
                "verbose_name": "About · Trajectory Entry",
                "verbose_name_plural": "About · Trajectory",
            },
        ),
        migrations.AlterModelOptions(
            name="trustedbylogo",
            options={
                "ordering": ["display_order", "pk"],
                "verbose_name": "Home · Trusted-By Entry",
                "verbose_name_plural": "Home · Trusted By",
            },
        ),
    ]
