# Generated by Django 5.2.17 on 2026-09-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_companyvalue_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to hide from the site without deleting.",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Used as the link's accessible label.", max_length=60
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Full profile URL, e.g. https://www.linkedin.com/company/…"
                    ),
                ),
                (
                    "icon_key",
                    models.CharField(
                        choices=[
                            ("linkedin", "LinkedIn"),
                            ("x", "X / Twitter"),
                            ("github", "GitHub"),
                        ],
                        help_text="Brand mark to display.",
                        max_length=40,
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer · Social Link",
                "verbose_name_plural": "Footer · Social Links",
                "ordering": ["display_order", "pk"],
                "abstract": False,
            },
        ),
    ]
