# Generated by Django 5.1.5 on 2026-05-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CaseStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                (
                    "client_name",
                    models.CharField(
                        help_text='Client name or "Confidential — Tier-1 Bank" when under NDA.',
                        max_length=120,
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        choices=[
                            ("banking", "Banking & Financial Services"),
                            ("government", "Government & Public Sector"),
                            ("energy", "Energy & Utilities"),
                            ("healthcare", "Healthcare"),
                            ("telecom", "Telecommunications"),
                            ("retail", "Retail & E-commerce"),
                            ("logistics", "Logistics & Transportation"),
                        ],
                        max_length=40,
                    ),
                ),
                ("region", models.CharField(default="GCC", max_length=80)),
                (
                    "summary",
                    models.CharField(help_text="Card summary.", max_length=280),
                ),
                ("challenge", models.TextField()),
                ("approach", models.TextField()),
                ("outcome", models.TextField()),
                (
                    "headline_metric",
                    models.CharField(
                        blank=True,
                        help_text='Hero number, e.g. "99.97%" or "−72%".',
                        max_length=40,
                    ),
                ),
                (
                    "headline_metric_label",
                    models.CharField(
                        blank=True,
                        help_text='Label for the hero metric, e.g. "Reduction in mean time to detect".',
                        max_length=80,
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="case_studies/"),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("is_published", models.BooleanField(default=True)),
                ("published_at", models.DateField(blank=True, null=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Case Study",
                "verbose_name_plural": "Case Studies",
                "ordering": ["display_order", "-published_at"],
            },
        ),
    ]
