# Generated by Django 5.2.17 on 2026-09-17 21:02

import apps.case_studies.models
import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_studies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casestudy",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.case_studies.models.case_study_image_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="casestudy",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                validators=[apps.core.validators.validate_string_list],
            ),
        ),
    ]
