# Generated by Django 5.1.5 on 2026-05-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobOpening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("slug", models.SlugField(blank=True, max_length=160, unique=True)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("soc", "Security Operations"),
                            ("threat_intel", "Threat Intelligence"),
                            ("cloud", "Cloud Security"),
                            ("offensive", "Offensive Security"),
                            ("engineering", "Platform Engineering"),
                            ("grc", "Governance, Risk & Compliance"),
                            ("sales", "Enterprise Sales"),
                            ("operations", "Operations"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full-time"),
                            ("contract", "Contract"),
                            ("intern", "Internship"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("junior", "Junior"),
                            ("mid", "Mid-level"),
                            ("senior", "Senior"),
                            ("principal", "Principal"),
                            ("lead", "Lead / Manager"),
                        ],
                        default="mid",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(default="Dubai, UAE", max_length=120)),
                ("is_remote_friendly", models.BooleanField(default=False)),
                ("summary", models.CharField(max_length=240)),
                ("description", models.TextField()),
                ("requirements", models.JSONField(blank=True, default=list)),
                ("nice_to_have", models.JSONField(blank=True, default=list)),
                ("is_published", models.BooleanField(default=True)),
                ("posted_at", models.DateField(auto_now_add=True)),
                ("closes_at", models.DateField(blank=True, null=True)),
                (
                    "apply_email",
                    models.EmailField(default="careers@sectrix.com", max_length=254),
                ),
            ],
            options={
                "verbose_name": "Job Opening",
                "verbose_name_plural": "Job Openings",
                "ordering": ["-posted_at", "title"],
            },
        ),
    ]
