# Generated by Django 5.2.17 on 2026-09-17 21:02

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobopening",
            name="nice_to_have",
            field=models.JSONField(
                blank=True,
                default=list,
                validators=[apps.core.validators.validate_string_list],
            ),
        ),
        migrations.AlterField(
            model_name="jobopening",
            name="requirements",
            field=models.JSONField(
                blank=True,
                default=list,
                validators=[apps.core.validators.validate_string_list],
            ),
        ),
    ]
